movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:movie_id>', views.detail, name='detail')
]

vidly/urls.py
from django import urls
from django.contrib import admin
from django.urls import path, include
from api.models import MovieResource
from . import views

movie_resource = MovieResource()


urlpatterns = [
    path('', views.home),
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('api/', include(movie_resource.urls))
]

api/models.py
# write
from django.db import models
from tastypie.resources import ModelResource
from movies.models import Movies
from django.contrib.auth.models import User
from tastypie.authentication import BasicAuthentication


class MovieResource(ModelResource):
    class Meta:
        queryset = Movies.objects.all()
        resource_name = 'movies'
        excludes = ['date_created']
        authentication = BasicAuthentication()

movies/models.py
from django.db import models
from django.utils import timezone

# Create your models here.


class Genre(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Movies(models.Model):
    title = models.CharField(max_length=255)
    release_year = models.IntegerField()
    number_in_stock = models.IntegerField()
    daily_rate = models.FloatField()
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
    date_created = models.DateTimeField(default=timezone.now)

    #actor_name = models.CharField(max_length=255)

    def __str__(self):
        return self.title


class Actor(models.Model):
    name = models.CharField(max_length=30)
    movie = models.ManyToManyField(Movies, through='Cast')

    def __str__(self):
        return self.name


class Cast(models.Model):
    movie = models.ForeignKey(Movies, on_delete=models.CASCADE)
    actor = models.ForeignKey(Actor, on_delete=models.CASCADE)

    class Meta:
        unique_together = [['movie', 'actor']]

api/views.py
from django.shortcuts import render

# Create your views here.

movies/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Movies
# Create your views here.


def index(request):
    movies = Movies.objects.all()
    return render(request, 'movies/index.html', {'movies': movies})
    # # SELECT * from movies_movie
    # Movies.objects.filter(release_year=1985)
    # # SELECT * from movies_movie WHERE release_year=1985
    # Movies.objects.get(id=1)


def detail(request, movie_id):
    # can use pk(primary key) instead of id
    #movie = Movies.objects.get(id=movie_id)
    movie = get_object_or_404(Movies, pk=movie_id)
    return render(request, 'movies/detail.html', {'movie': movie})

vidly/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'home.html')

movies/templates/movies/detail.html
{% extends 'base.html' %}
{% block content %}
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>Title</th>
                <th>Genre</th>
                <th>Stock</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{ movie.title }}</td>
                <td>{{ movie.genre  }}</td>
                <td>{{ movie.number_in_stock }}</td>
            </tr>
        </tbody>
    </table>
{% endblock  %}

movies/templates/movies/index.html
{% extends 'base.html' %}
{% block content %}
    <table class="table table-bordered table-hover">
        <thead>
        <tr>
            <th>Title</th>
            <th>Genre</th>
            <th>Stock</th>
            <th>Daily Rate</th>
        </tr>
        </thead>
        <tbody>
            {% for movie in movies %}
                <tr>
                    <td>
                        <!--<a href="/movies/{{ movie.id }}">{{movie.title}}</a>-->
                        <a href="{% url 'movies:detail' movie.id %}">{{movie.title}}</a>
                    </td>
                    <td>{{movie.genre}}</td>
                    <td>{{movie.number_in_stock}}</td>
                    <td>{{movie.daily_rate}}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock  %}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Vidly</title>
  </head>
  <body>
    <nav class="navbar navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Vidly</a>
        </div>
    </nav>
    <main class = "container">
    {% block content %}
    {% endblock %}
    </main>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html> 

templates/home.html
{% extends 'base.html' %}

{% block content %}
    <a href="{% url 'movies:index' %}">Movies</a>
{% endblock  %}